Repository AY2324S2-CS2103T-T17-2/tp, pull requests merged in 2024-04, with the labels that each got.

#77 Add comprehensive filtering options to user guide
  docs/UserGuide.md
Labels: documentation, requirements, priority.high

#79 Remove redundant ShowAllCommand
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/ShowAllCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ShowAllCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/employee/NameTest.java
  src/test/java/seedu/address/model/employee/PhoneTest.java
  src/test/java/seedu/address/model/employee/UniqueEmployeeListTest.java
Labels: priority.low

#126 Improve User Guide
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  docs/images/findAliceDavidResult.png
  docs/images/v1.3.png
Labels: documentation, requirements, priority.high

#129 Update user guide with command format
  docs/UserGuide.md
Labels: documentation, glossary, requirements, priority.high

#133 Credit Use of Model Stubs
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/model/ModelStub.java
  src/test/java/seedu/address/model/ModelStubWithEmployees.java
  src/test/java/seedu/address/model/ModelStubWithFilteredEmployeeList.java
Labels: documentation, priority.low

#131 Fix FilterCommand functionality in ContactSwift
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
Labels: bug, priority.high

#136 Improve code quality of task command classes
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/util/CommandUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: documentation, priority.medium

#140 In app msg
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/UnmarkTaskCommandParser.java
  src/main/java/seedu/address/model/task/Description.java
Labels: app-message

#141 Update Developer Guide for Enhanced Clarity and Accuracy
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
Labels: documentation, developer-guide, user-stories, use-case, non-functional-requirement, requirements, priority.medium

#137 Enhance EmployeeListCard UI by repositioning uid label
  src/main/resources/view/EmployeeListCard.fxml
Labels: UI, unique-userid

#146 Remove outdated information in DG
  docs/DeveloperGuide.md
Labels: developer-guide

#143 Revert "Enhance EmployeeListCard UI by repositioning uid label"
  src/main/resources/view/EmployeeListCard.fxml
Labels: priority.high

#150 Update filter command documentation
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
Labels: documentation, priority.high

#151 148-update-dg-implementation-details
  docs/DeveloperGuide.md
Labels: developer-guide

#153 Make UG More Comprehensive
  docs/UserGuide.md
Labels: documentation, priority.high

#155 Update Markbind
  docs/UserGuide.md
  docs/package-lock.json
  docs/package.json
Labels: bug, priority.high

#157 Update product name on website
  docs/_markbind/layouts/default.md
  docs/site.json
Labels: priority.high

#161 Update About-Us Page
  docs/AboutUs.md
  docs/images/Ui.png
  docs/images/hjungwoo01.png
Labels: documentation, AboutUs, priority.medium

#168 Revert to cf7c710c40ce2f851a2520ac81468ebba29c7b5b
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UpdatedEmployeeClassDiagram.puml
  docs/images/Ui.png
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
Labels: priority.high

#170 Update User Guide as before
  docs/UserGuide.md
Labels: priority.high

#172 Update UG
  docs/UserGuide.md
Labels: documentation, priority.high

#173 Fix internal hyperlink
  docs/DeveloperGuide.md
Labels: priority.high

#174 Fix UG bugs and update UML
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UpdatedEmployeeClassDiagram.puml
Labels: priority.high

#175 Remove Hyperlink from UG, update Ui image, add manual testing instructions
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
Labels: priority.high

#180 Fix DG Manual Testing Formatting
  docs/DeveloperGuide.md
Labels: developer-guide, priority.high

#182 Improve User Guide
  docs/UserGuide.md
  docs/images/filterTagRemoteResult.png
  docs/images/filterTagTeamRole.png
  docs/images/markTasks.png
  docs/images/unmarkTasks.png
Labels: documentation, priority.high

#184 Fix Formatting
  docs/UserGuide.md
Labels: bug, documentation

#185 Add data archive section, update ug, fix hyperlinks
  docs/UserGuide.md
  docs/package-lock.json
  docs/package.json
Labels: documentation, priority.high, user-guide-issue

#187 Fix typos in DG
  docs/DeveloperGuide.md
Labels: bug, documentation, priority.high

#188 169-uml-modifications
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: documentation, developer-guide

#191 Update ug typo
  docs/UserGuide.md
  docs/images/annotatedUi.png
Labels: documentation

#192 Add DG Appendix: Effort
  docs/DeveloperGuide.md
  docs/diagrams/FilterSequenceDiagram.puml
Labels: documentation, developer-guide, priority.high

#193 139-dg-planned-enhancements
  docs/DeveloperGuide.md
Labels: documentation, developer-guide

#195 Finalize UG
  docs/UserGuide.md
Labels: documentation, priority.high

#197 Fix typos in UG
  docs/UserGuide.md
Labels: documentation, priority.high

#199 Format DG
  docs/DeveloperGuide.md
Labels: documentation, developer-guide, priority.high
